from enum import StrEnum


class OptionalBetErrorCode(StrEnum):
    OPTIONAL_BET_INVALID_CAP_RATIO = "OPTIONAL_BET.INVALID_CAP_RATIO"
    OPTIONAL_BET_DUPLICATE_ASSET = "OPTIONAL_BET.DUPLICATE_ASSET"
    OPTIONAL_BET_ASSET_NOT_FOUND = "OPTIONAL_BET.ASSET_NOT_FOUND"
