from enum import StrEnum


class TargetErrorCode(StrEnum):
    TARGET_DUPLICATE_ASSET = "TARGET.DUPLICATE_ASSET"
    TARGET_INVALID_RATIO = "TARGET.INVALID_RATIO"
    TARGET_INVALID_TOLERANCE_BOUNDS = "TARGET.INVALID_TOLERANCE_BOUNDS"
    TARGET_TOTAL_MISMATCH = "TARGET.TOTAL_MISMATCH"
