from enum import StrEnum


class CliErrorCode(StrEnum):
    # Command Errors
    CLI_INVALID_COMMAND = "CLI.INVALID_COMMAND"

    # Parsing Errors
    CLI_INVALID_FLAG = "CLI.INVALID_FLAG"
    CLI_DUPLICATED_FLAG = "CLI.DUPLICATED_FLAG"
    CLI_MISSING_FLAG_VALUE = "CLI.MISSING_FLAG_VALUE"
    CLI_MISSING_REQUIRED_FLAG = "CLI.MISSING_REQUIRED_FLAG"
    CLI_INVALID_VALUE_TYPE = "CLI.INVALID_VALUE_TYPE"
