from enum import StrEnum


class StoreJsonErrorcodes(StrEnum):
    STORE_TARGET_NOT_FOUND = "STORE.TARGET_NOT_FOUND"
    STORE_SNAPSHOT_NOT_FOUND = "STORE.SNAPSHOT_NOT_FOUND"
    STORE_OPTIONAL_BET_NOT_FOUND = "STORE.OPTIONAL_BET_NOT_FOUND"
